# pull official base image
FROM python:3.11.4-slim-buster

# set work directory
RUN mkdir -p /home/backend
ENV HOME=/home/backend
ENV APP_HOME=/home/backend/eshop
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/mediafiles
WORKDIR $APP_HOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.dev.sh .
RUN sed -i 's/\r$//g' $APP_HOME/entrypoint.dev.sh
RUN chmod +x $APP_HOME/entrypoint.dev.sh

# copy project
COPY . $APP_HOME

# run entrypoint.sh
ENTRYPOINT ["/home/backend/eshop/entrypoint.dev.sh"]
